// <auto-generated />
namespace Flash.BitMarket.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Teesting2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Teesting2));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091923560_Teesting2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
